public class loopDemo {
   public void print_int_while(){
        integer count =1;
        while (count <=25){
            system.debug(count);
            count++;
        }
   
    }

public void print_N_number(integer n){
    for (Integer i =0; i< n; i++)
        system.debug(i);
}



public void print_N_odd_numbers(integer startInt, integer endInt){
    for (integer i= startInt; i< endInt; i++) {
        if(remainderI ==1){
            system.debug(1);
        }
    }
}


}