OperationsHelper exam = new OperationsHelper();
list<decimal> list1 = new list<Decimal> {0.98, 2.245, 89};
system.debug('The sum of list is '+ list1);
system.debug('The Avarage of all list elemetns => '+ OperationsHelper.averageOfList(list1));
system.debug('The highest of all list elemetns => '+ OperationsHelper.highestOfList(list1));
system.debug('The lowerst of all list elemetns => '+ OperationsHelper.lowestOfList(list1));